### ISSUE TITLE
TypeScript definitions are incorrect. 

### ISSUE THREAD

**Issue by torkelrogstad** [sweetalert2/sweetalert2-react-content#100]
`onOpen` and `onClose` does not take the popup as their argument, this should be updated in the definitions file.

**Comment by zenflow** [comment]
The definitions file doesn't define those methods.. https://github.com/sweetalert2/sweetalert2-react-content/blob/master/src/sweetalert2-react-content.d.ts

Is this an issue for https://github.com/sweetalert2/sweetalert2 ?

**Comment by limonte** [comment]
Definitions seem to be fine:

- https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts#L849
- https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts#L865

**Comment by torkelrogstad** [comment]
After wrapping my modals in `sweetalert2-react-content` the `onOpen` and `onClose` functions no longer received the modals as their argument, and I had to call `Swal.getPopup` to get a hold of if. So what I'm trying to say, is that this package should redefine the `onOpen` and `onClose` signatures to be `() => void` instead of `HTMLElement => void`. Similar to what you do for the other changed props: https://github.com/sweetalert2/sweetalert2-react-content/blob/master/src/sweetalert2-react-content.d.ts#L36

**Comment by zenflow** [comment]
I think it would be better to make the fix so that those methods are called with the modal as their argument, and keep things in alignment with how sweetalert2 behaves *without* this extension (sweetalert2-react-content).
