### ISSUE TITLE
Using shorthands with TypeScript

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-react-content#102]
When using with TypeScript

```ts
Swal.fire(<p>Shorthand works too</p>)
```

produces this error:

![image](https://user-images.githubusercontent.com/6059356/68528810-40c8b480-0300-11ea-8fbf-ce0e73848c71.png)

Which is correct per sweetalert2's [types](https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts#L23):

```ts
function fire(title?: string, message?: string, icon?: SweetAlertIcon): Promise<SweetAlertResult>;
```

The first param `title` is `string` and passing `<p>Shorthand works too</p>` should produce an error.

Should we deprecate shorthands or somehow support passing `Element` shorthands? What do you think about this @zenflow

**Comment by zenflow** [comment]
> Should we deprecate shorthands or somehow support passing Element shorthands? What do you think about this @zenflow 

I don't think we should ever downgrade the actual capabilities of a library in order to match typings. It should be the other way around; the typings should be made to match the actual types of the library.

**Comment by limonte** [comment]
Done, thank you @zenflow for the feedback!

`sweetalert2-react-content` is used in `sweetalert2-webpack-demo` now: https://github.com/sweetalert2/sweetalert2-webpack-demo/commit/962f5f6e18948d85883a0b7ba5d83c267aa39f37 :tada:

**Comment by limonte** [comment]
Reopening this issue as https://github.com/sweetalert2/sweetalert2/pull/1823 brought the regression described in https://github.com/sweetalert2/sweetalert2/issues/1822

**Comment by limonte** [comment]
Can't reproduce this issue anymore, shorthands seem to work as expected:

![image](https://user-images.githubusercontent.com/6059356/95679574-5ca59c00-0bdc-11eb-86b1-13d908ba2212.png)
