### ISSUE TITLE
Certain icons are appearing twice.

### ISSUE THREAD

**Issue by Isamyth** [sweetalert2/sweetalert2-react-content#104]
When using either the Warning, Info or Question icons, the mark appears twice. Success and Error icons do not display this.

`Swal.fire({
      title: 'Title',
      text: 'Yay or Nay?',
      icon: 'question',
      onClose: () => Swal.clickCancel(),
      confirmButtonText: 'Confirm',
      showCancelButton: true,
      cancelButtonText: 'Cancel',
    });`

![Screenshot 2019-11-25 at 11 10 26](https://user-images.githubusercontent.com/10710309/69535582-34855e00-0f74-11ea-9100-70b8fc41a375.png)

This is using sweetalert2 version 9.4.0 and sweetalert2-react-content version 2.0.2

**Comment by zenflow** [comment]
@Isamyth I tried to reproduce this on Glitch, using all the details you provided, but could not reproduce the issue. https://soapy-hubcap.glitch.me/ Can you please "remix" it to reproduce and demonstrate the issue?

**Comment by limonte** [comment]
> This is using sweetalert2 version 9.4.0

I doubt this based on the outlook of the buttons on your screenshot. You're probably using sweetalert2 8.x.x

**Comment by Isamyth** [comment]
@limonte I've checked my package.json file and it states I've installed sweetalert2 9.4.0

**Comment by Isamyth** [comment]
Found the issue, I was also using another library in the project, sweetalert2-react, which was causing the icons problem. The module has been removed since then and the alerts display as intended now.
