### ISSUE TITLE
How to get the states from inside the ajax request?

### ISSUE THREAD

**Issue by cptiwari20** [sweetalert2/sweetalert2-react-content#113]
`
 await MySwal.fire({
            title: <p>{inte.toUpperCase()}</p>,
            // footer: 'Copyright 2018',
            html: <Forms integration={inte} handleClose={MySwal.close()} handleSubmit={handleSubmit}/>,
            showCancelButton: true,
            focusConfirm: false,
            confirmButtonText:
                '<i class="fa fa-submit"></i> Submit!',
            confirmButtonAriaLabel: 'Submit',
            cancelButtonText: 'Cancel',
            showLoaderOnConfirm: true,
            preConfirm: () => {
                const isUserLogged = Auth.loginCheck();
                if (!isUserLogged) window.location = "/login";
                
                const token = JSON.parse(localStorage.getItem("login"));
                 async function handleFormSubmit(){
                  if (token) {
                    const id = Auth.decode("id");
                    const url = `${process.env.REACT_APP_ADMIN_SERVER_URL}/integrations/`;
                    
                    await axios
                      .post(url,
                        data, 
                          {
                          headers: {
                              authorization: token.token
                          },

                      })
                      .then(async data => {
                          // console.log(data)
                          setIntegrations(data.data);
                      }).catch(e => {
                          MySwal.showValidationMessage(
                            `Request failed: ${e.message}`
                          )
                      });
                  }
                }
                handleFormSubmit()
            },
          }).then(({isConfirmed}) => {
            if(isConfirmed){
               //do something

            }
          })
      }
  
`

`
data = {
...stateObj,
type: 'xyz'
}
`
When I submit the form, I get the stateObj Value == undefined. 
Its seems wired that, 
I think sweetAlert popup doesn't get any extra value from the state after fired once.
If it is so, how can I get the state.

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
