### ISSUE TITLE
Use custom button component

### ISSUE THREAD

**Issue by cardimajs** [sweetalert2/sweetalert2-react-content#116]
Hi, is possible to use custom button component?

any demo?

Thank you.

**Comment by zenflow** [comment]
@cardimajs Of course. It says in the README confirmButtonText & cancelButtonText can be React elements. React elements can be React components. Refer to the example in the README and replace `title: <p>Hello World</p>,` with `confirmButtonText: <MyCustomComponent />,`.

**Comment by cardimajs** [comment]
@zenflow Hi i try it, but i get this error using typescript

![image](https://user-images.githubusercontent.com/5782144/87247754-07ff5300-c42c-11ea-9938-53690e0e8f88.png)

**Comment by limonte** [comment]
> React elements can be React components. Refer to the example in the README and replace title: <p>Hello World</p>, with confirmButtonText: <MyCustomComponent />,.

That's actually incorrect, I just checked with https://github.com/sweetalert2/sweetalert2-webpack-demo and React elements aren't accepted as the value for `confirmButtonText`:

![image](https://user-images.githubusercontent.com/6059356/87251682-18d4b680-c476-11ea-8688-56a75e3c95ba.png)

![image](https://user-images.githubusercontent.com/6059356/87251675-0f4b4e80-c476-11ea-8119-7f83ce93ad61.png)
