### ISSUE TITLE
Custom Button on confirmButtonText

### ISSUE THREAD

**Issue by cardimajs** [sweetalert2/sweetalert2-react-content#117]
Hi, 
My custom button is inside a button, is possible to get only my custom button?
this is my code:

`MySwal.fire({
        icon: 'success',
        confirmButtonText: (<ThemeProvider theme={Theme}><Button color="success">confirmButtonText</Button></ThemeProvider>),
        title: 'Title'
      });`

![image](https://user-images.githubusercontent.com/5782144/87249235-40a32a80-c434-11ea-8092-786570403f6d.png)

and i get this error, button inside button

![image](https://user-images.githubusercontent.com/5782144/87249848-ee640880-c437-11ea-9643-174d372e0d3f.png)

Thank you.

**Comment by limonte** [comment]
I just release v3.0.3 which might help with this issue as well. @cardimajs could you please upgrade the `sweetalert2-react-content` dependency and check if the issue is still there or not?

**Comment by cardimajs** [comment]
@limonte hi, v3.0.3 fix typescript problem, but i have the same issue, my custom Button is inside another button.

Thank you.

**Comment by zenflow** [comment]
@cardimajs Sorry, `confirmButtonText` is an option.. `confirmButton` is **not** an option. 

You can disable the built-in confirm button and implement your own in the `html` option:

```js
MySwal.fire({
  showConfirmButton: false,
  html: (
    <ThemeProvider theme={theme}>
      <h1>Title</h1>
      <Button color="success" onClick={() => Swal.clickConfirm()}>
        OK
      </Button>
    </ThemeProvider>
  ),
})
```

**Comment by cardimajs** [comment]
@zenflow Thank you, it solve the problem.
