### ISSUE TITLE
Add `iconHtml` as a react element

### ISSUE THREAD

**Issue by mihaerzen** [sweetalert2/sweetalert2-react-content#146]
Hi!

It would be great if this library would also support `iconHtml` as a react element. We have a bunch of react element icons in our project and would be amazing if those can be re-used instead of rewriting them all into a css version.

I forked this project and tried adding this functionality but I'd appreciate some guidance. Here is the commit: https://github.com/mihaerzen/sweetalert2-react-content/commit/7bdd3efa28db6dd1ee1c02cc95f39c36225554c1

Specifically `swal.getIcon()` returns null and it could be the sweetalert library doesn't support this out of the box.

Any ideas?
Thank you very much!

**Comment by zenflow** [comment]
> Specifically swal.getIcon() returns null and it could be the sweetalert library doesn't support this out of the box

Don't forget to set the `icon` option alongside `iconHtml`! It took me a while to realize that this is required to use `iconHtml` in sweetalert2. It will determine the color of the circle and the inner content.

**Comment by limonte** [comment]
> Don't forget to set the `icon` option alongside `iconHtml`! It took me a while to realize that this is required to use `iconHtml` in sweetalert2. It will determine the color of the circle and the inner content.

There should be a warning for that!
