### ISSUE TITLE
can you pass react components in html prop?

### ISSUE THREAD

**Issue by DanielVain** [sweetalert2/sweetalert2-react-content#194]
<img width="585" alt="Screen Shot 2022-05-09 at 20 53 12" src="https://user-images.githubusercontent.com/80036840/167468814-f8d34465-85ec-45e1-93dc-2e3e86694e8a.png">

using Link component here breaks my alert and it shows nothing except the title.

does Sweetalert2-react-content support react components as html content?

**Comment by limonte** [comment]
My guess is that you're using React Router. If so you need to wrap what you're passing to `html` param into `BrowserRouter`:

```js
    MySwal.fire({
      html: (
        <BrowserRouter>
          ...
        </BrowserRouter>
      ),
    })
```

**Comment by GreenAsJade** [comment]
^^ This advice is "wrong", in the sense that if you do this you are creating a second routing context, which won't work the way you want.

It _will_ render the `<Link>`, but the rendered link won't do anything when you click on it.

https://stackoverflow.com/a/72690830/554807

**Comment by limonte** [comment]
Here's the official example of how to use SweetAlert2 + React Router: https://sweetalert2.github.io/recipe-gallery/sweetalert2-react-router.html
