### ISSUE TITLE
Can't resolve 'react-dom/client' in '/node_modules/sweetalert2-react-content/dist'

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [sweetalert2/sweetalert2-react-content#235]
It was working fine before but now giving this error after running the apps through the following commands

`yarn install`
`yarn start`

Also updated my packages to the following version but still getting this error :/

`"sweetalert2": "^11.6.15",`
`"sweetalert2-react-content": "^5.0.7"`

Node js version 
`v14.18.1`

Yarn version 
`1.22.19`

**Comment by limonte** [comment]
I recommend checking yarn warnings when installing/updating packages. Yarn would notify you about the wrong/missing react-dom package.

https://github.com/sweetalert2/sweetalert2-react-content/blob/main/package.json#L44

**Comment by ZeeshanAhmadKhalil** [comment]
For time being I switched to `sweetalert` but will try the above solution as well.
