### ISSUE TITLE
didOpen and willOpen (mixin) are not been fired anymore in 5x versions

### ISSUE THREAD

**Issue by zyc** [sweetalert2/sweetalert2-react-content#238]
After upgrading to 5x versions, the `didOpen` and `willOpen` callbacks are not fired anymore using `Swap.mixin` like this:

```
const willOpen = () => { console.log("I'm lost") };

const MySwal = withReactContent(
      Swal.mixin({
        willOpen,
      })
    );

MySwal.fire({ title: <p>Hello World</p> })
```

It was working fine in 4x versions.

**Comment by limonte** [comment]
This usage is undocumented and I'm not sure for now how it should be fixed.

This will work:

```ts
const willOpen = () => {
  console.log("I'm not lost")
}

const MySwal = withReactContent(Swal)

const MySwalMixin = MySwal.mixin({
  willOpen,
})

MySwalMixin.fire({ title: <p>Hello World</p> })
```

**Comment by zyc** [comment]
> This usage is undocumented and I'm not sure for now how/if it should be fixed.
> 
> This will work:
> 
> ```ts
> const willOpen = () => {
>   console.log("I'm not lost")
> }
> 
> const MySwal = withReactContent(Swal)
> 
> const MySwalMixin = MySwal.mixin({
>   willOpen,
> })
> 
> MySwalMixin.fire({ title: <p>Hello World</p> })
> ```

Thanks! It worked.
