### ISSUE TITLE
Wrong version in banners of dist files

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-react-content#48]
https://unpkg.com/sweetalert2-react-content@1.0.1/dist/sweetalert2-react-content.umd.js

Expected: 

```js
/** @preserve
  * package: sweetalert2-react-content v1.0.1
```

Actual: 

```js
/** @preserve
  * package: sweetalert2-react-content v1.0.0
```

I guess it's time to debug the `semantic-release` magic, nothing in life is free :)

**Comment by zenflow** [comment]
@limonte I think I can handle this, if you haven't started on it already

**Comment by limonte** [comment]
I haven't, go ahead 🚀
