### ISSUE TITLE
How to rerender swal content when state change

### ISSUE THREAD

**Issue by CacaoRick** [sweetalert2/sweetalert2-react-content#52]
When I change state, swal html content not render new state
example here: [https://codesandbox.io/s/l9q210kl2z](https://codesandbox.io/s/l9q210kl2z)

Is there any way to rerender content with new state?
Thanks

**Comment by CacaoRick** [comment]
Sorry I find solution.
Wrap a component and handle state inside.
https://codesandbox.io/s/7jz75rv136

**Comment by yechanpark** [comment]
@CacaoRick 
Thx for sharing your solution.
i solved my problem via your solution
👍

**Comment by RamtinNorouzi** [comment]
@CacaoRick 
thnx for solution

**Comment by ramilamparo** [comment]
If anyone is facing this issue, you may consider my solution here: https://github.com/sweetalert2/sweetalert2-react-content/issues/162#issuecomment-928928080

**Comment by viiqswim** [comment]
@CacaoRick solution also helped me. Thanks!

**Comment by Olamide9949** [comment]
I'm trying to update a counter when sweetalert pops up something like adding more item to cart but counter state is not updated? Any help?
