### ISSUE TITLE
Grant npm read-write access to sweetalert2 collaborators

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-react-content#57]
Currently, there are 5 SweetAlert2 collaborators: 

```sh
npm access ls-collaborators sweetalert2
{
  "toverux": "read-write",
  "samturrell": "read-write",
  "acupajoe": "read-write",
  "zen_flow": "read-write",
  "limonte": "read-write"
}
```

That will ensure that if bus-factor will happen to @limonte, `sweetalert2` might still be maintained by the rest of the collaborators.

On the other hand, 

```sh
npm access ls-collaborators sweetalert2-react-content
{
  "zen_flow": "read-write"
}
```

So, if something will happen to @zenflow, the project (or at least npm package name) will be :skull_and_crossbones: 

--- 

Is it okay for you @zenflow to align the list of collaborators with the one from sweetalert2? As I understand correctly, it could be done by running:

```sh
npm access grant read-write sweetalert2 
```

from the `sweetalert2-react-content` directory.

**Comment by zenflow** [comment]
The npm command was just hanging for me, so I added everyone as collaborators via the website. I don't see the updates on the public page yet.. I'm not sure, but the website gives me the impression that you will all need to accept some kind of email invitation.

I'll close this for now .. please reopen if there's any problem getting your name onto the list of collaborators for this package.. https://www.npmjs.com/package/sweetalert2-react-content

**Comment by zenflow** [comment]
@limonte did you get an invitation email? I am wondering why I am still showing as the only collaborator for the package on NPM..
