### ISSUE TITLE
Change button text after popUp whit React and sweetalert2-react

### ISSUE THREAD

**Issue by pcastro86** [sweetalert2/sweetalert2-react-content#63]
Hi! i m learning react and i trying to change my button text after sweetAlert2-react popup.
The original text on the button is 'ACTIVE' and
If i choose OK on the popup the text on the button must be 'activated' and if y choose CANCEL 'disabled'..
any help? 

here is my code:
`                <button onClick={() => this.setState({ show: true })}>ACTIVE</button>
                <SweetAlert
                  show={this.state.show}
                  showCancelButton={this.state.show}
                  title="Are you shore?"
                  onConfirm={() => this.setState({ show: false })}
                />`

Thanks!

**Comment by limonte** [comment]
> any help?

Yup. https://stackoverflow.com/questions/ask
