### ISSUE TITLE
Sweetalert2@8.x incompatibility

### ISSUE THREAD

**Issue by filippoitaliano** [sweetalert2/sweetalert2-react-content#66]
`"sweetalert2-react-content#sweetalert2@^7.18.0" doesn't satisfy found match of "sweetalert2@8.0.1"`

I tried even the previous 8.x version and it seems to be incompatilble. Any chance to get them working toghether at their letest releases?

**Comment by toverux** [comment]
yarn/npm indicates that it expects the peer dependency sweetalert2 to be compatible with range `^7.18.0`, but found `8.0.1`.
You have to install v7.x, as this library is not compatible with sweetalert2 v8.x yet (it's quite new).
The README has been [updated](https://github.com/sweetalert2/sweetalert2-react-content/commit/504d14981918ba127d37919d104dbbfeab841971) to reflect that.

**Comment by zenflow** [comment]
https://github.com/sweetalert2/sweetalert2-react-content/issues/69#issuecomment-463301501:

> > But the main one is v8 compatibility: #66
> > @zenflow if you maybe have some understanding of how to implement v8 compatibility please write it down
> 
> Can start by removing the usage of deprecated (and now removed) `setDefaults` from the tests.
> 
> Besides that I don't know at this point, because I haven't studied all the breaking changes to the `public` and `protected` API.
> 
> I do have this branch [feature/integrate-update-method](https://github.com/sweetalert2/sweetalert2-react-content/compare/feature/integrate-update-method) where I integrated the new `.update()` method. (Don't know why CI failed for it)
