### ISSUE TITLE
Making children vs Making and raising children

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-react-content#69]
In Western culture we're not just producing new human beings, we're raising (maintaining) them for a couple of first years. This approach seems to be the most efficient.

Unfortunately, OSS is still going with the primitive way of making an enormous amount of software packages (children), publishing them to the world with hopes that some of them will survive. Somehow.

GitHub is full of unmaintained abandoned packages with the single peak activity of their authors. I strongly dislike that part of OSS. Let's not be part of them and demonstrate with our own example that OSS can be not just about quantity, but about quality as well.

There are 5 raised issues (half a year old in average) and all of them could be resolved.

**Comment by limonte** [comment]
As I understand correctly, #33 will be resolved automatically by resolving #66

**Comment by limonte** [comment]
I can take care of #48

**Comment by limonte** [comment]
@zenflow I would ask you to take care of https://github.com/sweetalert2/sweetalert2-react-content/issues/49

There are 2 dev dependencies `zenflow-*` which are unmaintained and nobody except @zenflow are familiar with them. Using the default tooling is always better for maintainability.

**Comment by limonte** [comment]
But the main one is v8 compatibility: https://github.com/sweetalert2/sweetalert2-react-content/issues/66

@zenflow if you maybe have some understanding of how to implement v8 compatibility please write it down

**Comment by zenflow** [comment]
> There are 2 dev dependencies `zenflow-*` which are unmaintained and nobody except @zenflow are familiar with them. Using the default tooling for building/linting is always better for maintainability.

Opened PR #70 to replace zenflow-build-js-lib with rollup 

zenflow-lint-js is built with [standard-engine](https://github.com/standard/standard-engine) so it has a standard interface (plus some extras), with customized rules, and I rather like it. If you have an issue with it please open an issue to discuss there

**Comment by zenflow** [comment]
> But the main one is v8 compatibility: #66
> @zenflow if you maybe have some understanding of how to implement v8 compatibility please write it down

Can start by removing the usage of deprecated (and now removed) `setDefaults` from the tests.

Besides that I don't know at this point, because I haven't studied all the breaking changes to the `public` and `protected` API. 

I do have this branch [feature/integrate-update-method](https://github.com/sweetalert2/sweetalert2-react-content/compare/feature/integrate-update-method) where I integrated the new `.update()` method. (Don't know why CI failed for it)

**Comment by zenflow** [comment]
p.s. We really should have considered how breaking changes in sweetalert2 would affect extensions/enhancers *before* committing to them.

**Comment by zenflow** [comment]
Closing this since there are already issues for most of the items brought up. Anything else that is really an issue you can open an issue for.
