### ISSUE TITLE
All builds failing due to error in `coveralls` 

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2-react-content#71]
```
/home/travis/build/sweetalert2/sweetalert2-react-content/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
The command "npm test && cat ./coverage/lcov.info | coveralls" exited with 1.
```
Reference: https://travis-ci.org/sweetalert2/sweetalert2-react-content/builds/494904266

**Comment by zenflow** [comment]
I already tried a bunch of troubleshooting, including this https://github.com/nickmerwin/node-coveralls/issues/166#issuecomment-451315548

Since I deleted and re-added the repo on the coveralls site, which removed all history, the [page for this repo](https://coveralls.io/github/sweetalert2/sweetalert2-react-content) will show installation instructions until some data is successfully sent to coveralls.

**Comment by zenflow** [comment]
It's somehow lost in the build history on travis.org, but this problem originally came up around 8 or 9 hours ago in a cron build for the baster branch.

**Comment by zenflow** [comment]
I can't get it to work, or guess why it suddenly stopped working, so for now I'll leave it and hope that later it suddenly starts working again.

**Comment by zenflow** [comment]
If the issue persists, I suggest we just stop using coveralls for now, and open an issue to add it back later. We can still see the test coverage in the build log.

**Comment by limonte** [comment]
It suddenly started to work again. I restarted builds for #70 and they are passing. Closing this issue.
