### ISSUE TITLE
sweetalert2-react-content doesn't work in stackblitz

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2-react-content#9]
stackblitz is an amazing sandbox for react, it's blazing fast and comfortable to use.

Here's the simple project with sweetalert2-react-content: https://stackblitz.com/edit/react-ndncml?file=index.js

If you uncomment two lines:

```js
import withReactContent from 'sweetalert2-react-content'
console.log(withReactContent)
```

There will be a strange notification about missing packages:

![](https://i.imgur.com/7fcRW6R.png)

**Comment by zenflow** [comment]
Thanks for reporting @limonte .. apparently I did not read the webpack documentation close enough

It works now: https://stackblitz.com/edit/react-p1a1go?file=index.js

**Comment by limonte** [comment]
Lovely! Can't wait for 1.0.0 :tada:

**Comment by zenflow** [comment]
@limonte Me too!

**Comment by zenflow** [comment]
Just leaving a note here for myself..

Similar to stackblitz and also awesome: codesandbox.io
